import { DurableObject } from 'cloudflare:workers'
import type { GameState } from '../types'
import { applyAction, emptyGame } from '../game/reducer'
import type { ClientMessage, ServerMessage } from '../game/protocol'

// `Env` is the global interface generated by `wrangler types` into
// worker-configuration.d.ts; it already types GAME_ROOM + ASSETS from the
// bindings in wrangler.jsonc. We use it rather than redeclaring a local one.

const RECENT_LIMIT = 500

interface Persisted {
  state: GameState
  seq: number
  recentActionIds: string[]
}

export class GameRoom extends DurableObject<Env> {
  private data: Persisted = { state: emptyGame, seq: 0, recentActionIds: [] }

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env)
    ctx.blockConcurrencyWhile(async () => {
      ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS room (k TEXT PRIMARY KEY, v TEXT NOT NULL)`)
      const row = ctx.storage.sql
        .exec<{ v: string }>(`SELECT v FROM room WHERE k = 'data'`).toArray()[0]
      if (row) this.data = JSON.parse(row.v) as Persisted
    })
  }

  private persist() {
    this.ctx.storage.sql.exec(
      `INSERT INTO room (k, v) VALUES ('data', ?) ON CONFLICT(k) DO UPDATE SET v = excluded.v`,
      JSON.stringify(this.data),
    )
  }

  private snapshot(): ServerMessage {
    return { type: 'snapshot', state: this.data.state, seq: this.data.seq, recentActionIds: this.data.recentActionIds }
  }

  private broadcast(msg: ServerMessage) {
    const raw = JSON.stringify(msg)
    for (const ws of this.ctx.getWebSockets()) ws.send(raw)
  }

  async fetch(request: Request): Promise<Response> {
    // Seed (create): POST the initial GameState; only succeeds on an empty room.
    if (request.method === 'POST') {
      const body = (await request.json()) as { state?: unknown }
      const state = body?.state as GameState | undefined
      // Reject malformed bodies — seeding `undefined` here would brick the room.
      if (!state || !Array.isArray(state.players) || !Array.isArray(state.log)) {
        return Response.json({ ok: false, seeded: false })
      }
      const empty = this.data.state.players.length === 0 && this.data.state.log.length === 0
      if (empty) { this.data = { state, seq: 0, recentActionIds: [] }; this.persist() }
      return Response.json({ ok: true, seeded: empty })
    }
    // Join: WebSocket upgrade.
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 })
    }
    const { 0: client, 1: server } = new WebSocketPair()
    this.ctx.acceptWebSocket(server)
    server.send(JSON.stringify(this.snapshot()))
    return new Response(null, { status: 101, webSocket: client })
  }

  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer) {
    let msg: ClientMessage
    try {
      msg = JSON.parse(typeof raw === 'string' ? raw : new TextDecoder().decode(raw)) as ClientMessage
    } catch { return }
    if (msg.type !== 'action') return

    // Dedup: a resent action that's already applied → resync the sender only.
    if (this.data.recentActionIds.includes(msg.actionId)) {
      ws.send(JSON.stringify(this.snapshot()))
      return
    }
    // Guard against a malformed action, then apply authoritatively, PERSIST
    // FIRST, then broadcast. A thrown reducer error must not bump seq or persist.
    if (!msg.action || typeof msg.action !== 'object') {
      ws.send(JSON.stringify({ type: 'error', message: 'invalid action' } satisfies ServerMessage))
      return
    }
    try {
      this.data.state = applyAction(this.data.state, msg.action)
      this.data.seq += 1
      this.data.recentActionIds = [...this.data.recentActionIds, msg.actionId].slice(-RECENT_LIMIT)
      this.persist()
      this.broadcast({ type: 'action', actionId: msg.actionId, action: msg.action, seq: this.data.seq })
    } catch {
      ws.send(JSON.stringify({ type: 'error', message: 'action failed' } satisfies ServerMessage))
    }
  }

  async webSocketClose(ws: WebSocket, code: number) {
    // Presence is deferred; just close cleanly.
    // TODO(presence): broadcast a presence delta here.
    try { ws.close(code) } catch { /* already closing */ }
  }

  async webSocketError() {
    // TODO(presence): drop from presence set.
  }

  // TODO(cleanup): set a storage alarm to expire idle rooms after N days.
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url)
    const m = url.pathname.match(/^\/api\/room\/([A-Za-z0-9]+)(?:\/ws)?$/)
    if (m) return env.GAME_ROOM.getByName(m[1].toUpperCase()).fetch(request)
    return env.ASSETS.fetch(request)
  },
} satisfies ExportedHandler<Env>
